use YAML.dump to serialize a simple hash to a file
The data for this file resource's content is really a simple Ruby Hash
built up from node attributes, not a node object itself. Instead of
relying on the .to_yaml behavior previously patched onto Hash, use
plain old Ruby YAML.dump with the Hash instead.

Resolves new "NoMethodError: undefined method 'to_yaml' for Hash" error
when chefspec'ing.

Signed-off-by: Robb Kidd <rkidd@chef.io>