pin rubygems to 2.6.x
RubyGems 2.7.0-.3 seems to break the omnibus build with:

```
ERROR:  Error installing bundler:
"bundle" from bundler conflicts with /opt/supermarket/embedded/bin/bundle
```

Pinning to latest 2.6.x to fix the pipeline for release.

PEOPLE OF THE FUTURE, this pin should get revisited.

Signed-off-by: Robb Kidd <rkidd@chef.io>